### PR TITLE
Use `nf` instead of `whnf` in Haskell benchmarks

### PR DESCRIPTION
**Pull request by bryce-anderson**

### CODE REVIEW

**Comment by Geal** [comment]
Hi!

Could you update the code to merge correctly with https://github.com/Geal/nom_benchmarks/pull/5 (which is in master now)? I could try to do the merge myself, but I am not sure I would be able to keep the performance benefits. My Haskell-fu is not that strong...

**Comment by bryce-anderson** [comment]
Upon further inspection, I don't think that #5 makes the evaluation strict. The code [here](https://github.com/Geal/nom_benchmarks/blob/master/haskell-cereal/src/Main.hs#L34) is never run. This can be verified using a trace statement. This is the bulk of the execution so the only thing being benchmarked is the creation of thunks. Furthermore, I'm not sure why `mp4Box` doesn't go something like this: (**EDIT:** see next comment to understand why its not this way)

``` haskell
mp4Box :: Get LV
mp4Box = do
  length <- fmap fromIntegral getWord32be
  let remaining = length - 4
  value <- anyBox remaining -- note removal of the explicit evaluation and getBytes
  return (LV length value)
```

Maybe there is a reason for it, but I think that should also be correct and more idiomatic. 

I believe the `[LV]` result of `mp4Parser` is also still lazy. To force evaluation I added a `length` call which should force the evaluation of the cells as well otherwise the length cannot be known. However, with these modifications I get a parser failure with `Failed reading: Type not recognized`. [I've made a branch with that code for inspection](https://github.com/bryce-anderson/nom_benchmarks/commit/017e3f8b80cf38cf46229040846270776a80f563). I suspect the parser is just wrong in some manner, but I don't know anything about the format to be sure.

I'm not a Haskell pro so all this could be nonsense. @Gabriel439 may have some opinion on it, and is certainly more experienced that I.

**Comment by bryce-anderson** [comment]
Ah, it now occurs to me why `mp4Box` is the way it is: only the `"ftyp"` directive will consume its block. If `skip (l -4) >> return WhateverBOX` is used in the `anyBox` function for non "ftyp" directives, the parser works in the fashion I detailed above. I'm not sure of its performance implications. 

I don't think this has any barring on the lazy issues.

**Comment by Geal** [comment]
yes, the mp4 parser is voluntarily incomplete, because writing a complete one just for a benchmark would have been improductive

**Comment by bryce-anderson** [comment]
So I don't know how to move this forward, or if we should just drop it. I believe the current master implementation of the cereal benchmarks are still using thunks to avoid computation; lazy evaluation is pretty challenging to dissect. This PR is strict in both cereal and attoparsec benchmarks as enforced by the deepseq package.

It should be noted that a real parser would actually benefit greatly from thunks. It may happen to be that all blocks would not be needed and therefor a real work load could avoid parsing discarded blocks. However, that doesn't seem appropriate for this benchmark as no data is actually needed.

**Comment by Gabriella439** [comment]
This was my mistake.  I'm used to using unboxed or storable vectors where weak-head-normal-form is the same as normal form.  You could just implement `NFData` for the types again and `deepseq` the result to fix the benchmark.

**Comment by bryce-anderson** [comment]
Ok, the PR is updated to use `vector` in both attoparsec and cereal. The deepseq package should be forcing evaluation so it should be a good comparison.

Benchmark results (Intel Core i5-2500K, Ubuntu 14.10 VM):
**Attoparsec**

```
benchmarking IO/small
time                 1.107 μs   (1.067 μs .. 1.149 μs)
                     0.994 R²   (0.990 R² .. 0.999 R²)
mean                 1.103 μs   (1.083 μs .. 1.124 μs)
std dev              71.27 ns   (55.55 ns .. 89.38 ns)
variance introduced by outliers: 76% (severely inflated)

benchmarking IO/big buck bunny
time                 1.116 μs   (1.063 μs .. 1.163 μs)
                     0.988 R²   (0.986 R² .. 0.992 R²)
mean                 1.130 μs   (1.098 μs .. 1.166 μs)
std dev              121.6 ns   (110.0 ns .. 139.1 ns)
variance introduced by outliers: 90% (severely inflated)
```

**cereal**

```
benchmarking IO/small
time                 881.1 ns   (869.7 ns .. 894.5 ns)
                     0.999 R²   (0.998 R² .. 1.000 R²)
mean                 870.4 ns   (865.7 ns .. 877.9 ns)
std dev              19.42 ns   (14.22 ns .. 29.80 ns)
variance introduced by outliers: 28% (moderately inflated)

benchmarking IO/big buck bunny
time                 860.1 ns   (855.1 ns .. 866.4 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 864.6 ns   (860.2 ns .. 870.9 ns)
std dev              16.47 ns   (13.25 ns .. 21.14 ns)
variance introduced by outliers: 22% (moderately inflated)
```

**nom**

```
running 2 tests
test bigbuckbunny_test ... bench:       206 ns/iter (+/- 12)
test small_test        ... bench:       218 ns/iter (+/- 17)

test result: ok. 0 passed; 0 failed; 0 ignored; 2 measured
```

Didn't run hammer.

**Comment by Gabriella439** [comment]
It's a better comparison now.  There are still issues with the Haskell code.  The problem with naive use of `deepseq` is that it evaluates everything twice (and it basically destroys the cache since you are retraversing the entire structure to force everything).  This is why most Haskell data structures instead adopt a "evaluate as you go" policy where you keep the data structure strict at all times instead of going over the structure again in one final pass.

However, don't let that block this pull request.  Merge this in and I'll submit a new one that uses a more optimal strategy for keeping the structure strict.

**Comment by Geal** [comment]
Thanks for this PR! Any idea why the variance is so high for the cereal parser?

**Pull request merged**
